AllCops:
  Exclude:
    - "**/*.slim"
    - "vendor/**/*"
    - "db/schema.rb"

Lint/EndAlignment:
  AlignWith: variable

Metrics/LineLength:
  Max: 90

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# メソッド呼び出しの行から1段階インデントする
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/Documentation:
  Enabled: false

# メソッドを複数行に分けて記述したとき、`.` は行末に配置する
Style/DotPosition:
  EnforcedStyle: trailing

# `lambda` のブロック内が複数行になるときもRuby 1.9から入った `-> {}` 記法で書く
# `lambda` より `->` のほうがすっきりするため。
Style/Lambda:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes
